version: "3.8"

services:
  tools:
    image: ${REGISTRY}sitecore-docker-tools-assets:${VERSION:-latest}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE}
        BUILD_IMAGE: ${BUILD_IMAGE}
    # Windows-specific configuration for ltsc2025
    deploy:
      resources:
        limits:
          memory: 4G